version: '3.7'

services:
  delivery-control:
    container_name: delivery-control
    image: delivery-control
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./build:/usr/src/app/build
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - .env:/usr/src/app/.env
    networks: 
      - delivery-control 
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3316:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=delivery-control
    networks:
      - delivery-control
networks:
  delivery-control:
    driver: bridge
